WIP: configuring travis-ci tests
saltstack-formulas/logrotate-formula pull request #34
Opened 2018-08-23 11:08 UTC by daks

Still WIP

2018-08-23 12:30 UTC, javierbertoli commented on .travis.yml
> +  - bundle exec kitchen destroy
Hi @daks, perhaps you can use the files in the [packages formula](https://github.com/saltstack-formulas/packages-formula/) or the [apache formula](https://github.com/saltstack-formulas/apache-formula/) as a reference?

Ie, the [.travis.yml file](https://github.com/saltstack-formulas/apache-formula/blob/master/.travis.yml) can be greatly simplified and little is needed to get it up and running.

2018-09-28 01:53 UTC, javierbertoli requested changes
@daks, I tried the changes I'm suggesting locally and they worked. I think that with those we can get this working. Would you submit them when you have some time?

2018-09-28 01:53 UTC, javierbertoli commented on .kitchen.yml
> +
You need to add

```yaml
  run_command: /lib/systemd/systemd
```

so the `service.sls` state can run.

2018-09-28 01:53 UTC, javierbertoli commented on .kitchen.yml
> +  is_file_root: true
You need to remove this line. It defines the root path for this formula, and it's at odds with the path defined in `state_top` below (that's why it's not finding the states).

2018-09-28 01:53 UTC, javierbertoli commented on .kitchen.yml
> +  require_chef: false
This `require_chef: false` line is 3 times, these 2 can be removed.

2018-09-28 01:53 UTC, javierbertoli commented on .kitchen.yml
> +
You can re-enable the tests here, with

```yaml
verifier:
  name: inspec
  reporter:
    - cli
  inspec_tests:
    - path: test/integration/default
```

2018-10-16 14:50 UTC, daks commented
@javierbertoli thanks to your help (and more available time), I pushed new code to add travis tests. Those work now, but tests on CentOS fail :(

2018-10-16 18:35 UTC, javierbertoli commented
Checking locally, it seems RedHat family does not use a systemd timer to run logrotate, but a plain old cron, so the `service` state fails. 

It seems this PR is already finding bugs in the formula :smile: 

I think we'd probably need a conditional on that state file, to run only on Debian family and eventually add tests for `service running` / `cron existence` depending on the family?

wdyt?

2018-10-17 12:56 UTC, daks commented
> It seems this PR is already finding bugs in the formula smile

and this is great!

> I think we'd probably need a conditional on that state file, to run only on Debian family and eventually add tests for service running / cron existence depending on the family?

I'm not fan of conditionals in the state, but maybe there is not better option. Eventually it can be activated with an option defined (depending of OS) in the map.jinja.

In any case, I'm not sure I'll be able to look at it soon so don't you think it would be better to merge this PR (eventually without the faulty test) and create an issue for later?

2018-10-17 13:40 UTC, javierbertoli commented
> I'm not fan of conditionals in the state, but maybe there is not better option. Eventually it can be activated with an option defined (depending of OS) in the map.jinja.

Neither am I, but there are a few other formulas with states that are apply depending on the OS, as some OS differ this much (ie, systemd timer vs. cron), so I think in this case it would be the quickest solution.

> In any case, I'm not sure I'll be able to look at it soon so don't you think it would be better to merge this PR (eventually without the faulty test) and create an issue for later?

Problem is, what's failing is a state file, not a test. The formula is not applying completely because that state fails. I'll try to get a few minutes later today, modify these things we're discussing and probably merge this PR + push another PR to fix that part of the formula. Are you OK with this?

2018-10-17 13:57 UTC, daks commented
I'm ok.

2018-10-26 11:44 UTC, merged

2018-10-26 11:45 UTC, javierbertoli commented
Where I said 'a few minutes later today' should have read 'these days' but well... merged. :smile: 
Thanks, @daks.