feat(hourly): Add configuration to enable hourly jobs
saltstack-formulas/logrotate-formula pull request #60
Opened 2021-11-23 20:32 UTC by mdschmitt

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Not unless existing pillar values for clients have "hourly" set in their job configurations.  ...in which case, they already don't work straight-out-of-the-box.

### Related issues and/or pull requests

### Describe the changes you're proposing

### Pillar / config required to test the proposed changes

### Debug log showing how the proposed changes work

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2021-11-25 19:23 UTC, myii requested changes
Thanks for the PR, @mdschmitt.  Some initial feedback for the time being.

After numerous discussions, essentially we _never_ use `salt['pillar.get']()` in our formulas.  Let me give some brief explanations:

1. `salt['pillar.get']()` is unnecessary since `map.jinja` already merges all of the elements under one key, which is [`logrotate`](https://github.com/saltstack-formulas/logrotate-formula/blob/da488f4bf75518d8018193792da0f7d510d82c43/logrotate/map.jinja#L45) for this formula.
1. There have been many reasons given why non-secret data shouldn't be stored under pillars (e.g. pillars are rendered on the master); so we're in the process of moving to `config.get` instead, which has already been adopted by this formula in [`map.jinja`](https://github.com/saltstack-formulas/logrotate-formula/blob/da488f4bf75518d8018193792da0f7d510d82c43/logrotate/map.jinja#L13).

Hence, using `salt['pillar.get']()` inline is unnecessary duplication, longer to write, more difficult to review (not a single point for all data being used by the formula), not to mention prevents end-users from providing their data from sources other than pillar (e.g. SDB).

You should find it relatively simple to access the data via the `logrotate` key.  Let me know if you face any issues.  Once you're done, please amend/rebase your commit(s) and force-push back here -- thanks.

2021-11-25 19:28 UTC, myii commented on logrotate/config.sls
> +{% if ns.hourly == True %}
```suggestion
{%- if ns.hourly %}
```

The above is sufficient.  Note also the use of Jinja whitespace control (`{%- ... %}`).  Again, there have been a number of discussions about this and we've found this structure to be effective in nearly all situations.  There are rare cases where you need to apply the post-whitespace control (`{% ... -%}`) but we're agreed that we should never use pre- and post-whitespace control (`{%- ... -%}`).

One of the main benefits of this is working through the debug output, showing how states have been rendered.  It is also very useful in templates.

2021-12-09 23:37 UTC, mdschmitt commented
@myii , how's this look?

2021-12-20 23:47 UTC, mdschmitt commented
No major rush, but any word on this?

2022-01-05 20:22 UTC, mdschmitt commented
@myii , dropping another *bump* in here.  Any feedback on my revisions?

2022-01-14 00:33 UTC, mdschmitt commented
Latest CI failure because ArchLinux properly uses systemd timers rather than cron.  Requires deeper code tweakage to properly provide for.  This PR on hold until I can get that to be better.

2022-01-14 11:17 UTC, myii commented
@mdschmitt Thanks for the additions.  I've tested some changes in my own fork to ensure Arch Linux is working as well.  I'll push those here and merge this PR shortly.

One question remains: which reference did you use for the `/etc/logrotate.hourly.d/...` path?  I couldn't find any mention of it in the upstream repo:

* https://github.com/logrotate/logrotate/search?q=%22logrotate.hourly.d%22&type=code

2022-01-14 11:45 UTC, myii approved these changes

2022-01-14 12:27 UTC, merged

2022-01-17 22:49 UTC, mdschmitt commented
Wow @myii , thank you so much for doing this.  You beat me to writing the kitchen test and I definitely would have ended up rewriting things to allow for Arch.  Folding in `cron-formula` as a dependency is much cleaner though.

As far as the naming for "logrotate.hourly.d", it was just a logical canonicalization of "logrotate.d" with the explicit addition of "hourly" since hourly isn't out-of-the-box functionality.  Inspiration taken from https://sleeplessbeastie.eu/2018/07/11/how-to-execute-logrotate-every-hour

2022-01-18 22:42 UTC, myii commented
No problem -- thanks for the reference, @mdschmitt.